name: Windows build

on: [ push, pull_request ]

jobs:

  build:
    runs-on: windows-latest
    steps:
    - name: git configure long path and autocrlf
      run: |
        git config --global core.longpaths true
        git config --global core.autocrlf input

    - uses: actions/checkout@v2
    
    - run: git config --get core.autocrlf

    - uses: actions/setup-java@v2
      with:
        java-version: '11.0.10'
        java-package: jdk
        architecture: x64
        distribution: 'adopt'

    - name: Build
      run: ./gradlew build
