name: Windows build

on: [ push, pull_request ]

jobs:

  build:
    runs-on: windows-2019
    steps:    
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v2
      with:
        java-version: '11.0.10'
        java-package: jdk
        architecture: x64
        distribution: 'adopt'

    - name: Build
      run: ./gradlew build
